networks:
  aurx-internal:
    external: False

name: aurx

services:
  host:
    build:
      context: ./
      dockerfile: Containerfile
      target: one-stage
    command: ["sleep", "10000"]
    networks:
    - aurx-internal
    environment:
      AURX_SOURCE_PATH: /home/archlinux/.src
    restart: no
 
